image_type_tezi_run.bbclass: fix recovery.bin creation
Looks like later SCFW versions don't like us adding the tezi.itb as an AP image leading to the following un-recoverable error during boot:

Hello from SCU (Build 3332, Commit cb6f758b, May 20 2019 10:53:24)

DDR frequency = 1596000000
Error: bad image partition, multiple primary

Fix this by rather appending it as data just like the imx-mkimage README suggests.

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>