tezi.conf: Drop predefined dtb addresses
meta-toradex-nxp layer has predefined variables for an fdt
subimage, that are used to define the load address of the fdt for
FIT Image. The target address space overlaps with the initramfs
image. It causes error in loading FDT image and fails
staring kernel.

I.e. for Colibri iMX6:
...
   Using 'config@imx6dl-colibri-eval-v3.dtb' configuration
   Trying 'fdt@imx6dl-colibri-eval-v3.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x127a3414
     Data Size:    61727 Bytes = 60.3 KiB
     Architecture: ARM
     Load Address: 0x12100000
     Hash algo:    sha1
     Hash value:   249f02a193a499185137642390f6c9a977055ff7
   Verifying Hash Integrity ... sha1+ OK
Error: fdt overwritten
   Booting using the fdt blob at 0x2ffc2299
data abort
pc : [<2ff8af98>]          lr : [<2ff8af95>]
reloc pc : [<17815f98>]    lr : [<17815f95>]
sp : 2df6b248  ip : 00000000     fp : 0000071f
r10: 00000001  r9 : 2df74ed0     r8 : 00000002
r7 : 2ffd2a94  r6 : 2ffd2a90     r5 : 2ffd29f0  r4 : 2ffc2299
r3 : 2ff8c511  r2 : c0000000     r1 : 00000000  r0 : 0000002c
Flags: nzcv  IRQs off  FIQs off  Mode SVC_32 (T)
Code: f029 ff7d 9c05 6034 (6863) ba1b
Resetting CPU ...

Drop predefined values UBOOT_DTB_LOADADDRESS_* to let Easy Installer
kernel start successfully.

Related-to: TEI-775
Related-to: TEI-745
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>