image_type_tezi_run: create image.json after FIT image
Currently image.json gets created after the do_rootfs task. This
is too early since image.json needs to get the FIT images file
size. This lead to a build failure typically seen on very first
builds:
Exception: subprocess.CalledProcessError: Command '['du', '-kLc', '/workdir/build/../deploy/images/apalis-imx6/tezi.itb']' returned non-zero exit status 1

Fix this by calling the image.json creation function between
FIT image assembling and final tar file generation.

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>