image_type_tezi_run: fix vardepsexclude task name typo
do_image_teziimg does not exist. The vardepsexclude flag was silently
ignored, leaving DISTRO_VERSION, TDX_VER_ID and DATE in the basehash
of do_image_tezirunimg. When DATE changes at midnight during a build,
the basehash differs between parse passes causing:

  ERROR: When reparsing ...do_image_tezirunimg, the basehash value changed

Confirmed via bitbake -Sprintdiff which explicitly reported:
  Variable DATE value changed from '20260428' to '20260429'

Rename do_image_teziimg[vardepsexclude] to do_image_tezirunimg[vardepsexclude].

Related-to: AUT-3192
Fixes: 8afcde346e3e ("versioning: change to use latest toradex versioning scheme")
Signed-off-by: David Arnold <david.arnold@toradex.com>