u-boot-distro-boot: Fix boot.cmd.in location
During the forward port of commit 8d34b1de07c1
("u-boot-distro-boot: make all boot.cmd transformations in one pass"),
we forgot to update a reference from ${WORKDIR} to ${S}, leading to the
file boot.cmd.in not being found. Fix that.

This fixes the following error:
  | sed: can't read [...]/u-boot-distro-boot/1.1/boot.cmd.in: No such file or directory
  | WARNING: exit code 2 from a shell command.
  NOTE: recipe u-boot-distro-boot-1.1-r0: task do_compile: Failed
  ERROR: Task (/workdir/oe/build/../layers/meta-toradex-tezi/recipes-core/u-boot-distro-boot/u-boot-distro-boot_1.1.bb:do_compile) failed with exit code '1'

Fixes: 8d34b1de07c1 ("u-boot-distro-boot: make all boot.cmd transformations in one pass")
Signed-off-by: Ernest Van Hoecke <ernest.vanhoecke@toradex.com>