distro: tezi: opt out of using opengl and vulkan
OE Core enabled opengl and vulkan by default [1], which leads to
incompatible package configurations for qtbase and qtwayland.
That leads to the following errors:

ERROR: Feature 'eglfs' was enabled, but the pre-condition '!config.android && !config.darwin && !config.win32 && !config.wasm && features.egl' failed.
ERROR: Feature 'wayland-vulkan-server-buffer' was enabled, but the pre-condition 'features.wayland-server && features.vulkan && features.opengl && features.egl && tests.vulkan-server-buffer' failed.

DISTRO_FEATURES_BACKFILL was used to enable these, allowing us to opt
out with DISTRO_FEATURES_BACKFILL_CONSIDERED.

[1] commit 2e1e7c86064c ("bitbake.conf: Enable opengl ptest multiarch wayland vulkan in DISTRO_FEATURES by default")

Signed-off-by: Ernest Van Hoecke <ernest.vanhoecke@toradex.com>