weston: fix missing return parameter in patch
Fixes the following build time error thrown with GCC-14:
| ../weston-9.0.0/compositor/screen-share.c:1194:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
|  1194 |                 return;

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>